#!/usr/bin/env node
const fs = require('fs');

// define ./src scripts to convert here
//
let scripts = [
    'index',
    'folderUtils',
];

//  preparing cjs files for conversion
//  ----------------------------------
//  comment out import statements with //import at line start
//  put /*cjs*/ at line start of function declaration (where "export" will go)
//  start multi-line cjs-only code with a line starting with //cjs-start
//  end multi-line cjs-only code with a line starting with //cjs-end


for(s in scripts){
    let cjsText = fs.readFileSync( "./src/"+scripts[s]+".js", 'utf8');
    let esmText = processCJS( cjsText );
    fs.writeFileSync( "./lib/"+scripts[s]+".js", esmText );
}
function processCJS(text){
    text = text.split(/\n/);
    let esm = "";
    for(var i=0;i<text.length;i++){
        let line = text[i];
        line = line.replace(/^\/\*cjs\*\/ /,'export ');
        line = line.replace(/^\/\/ import/,'import');
        line = line.replace(/^\/\/ cjs-start/,'// cjs-start\n/*');
        line = line.replace(/^\/\/ cjs-end/,'*/\n// cjs-end');
        esm += line + "\n";
    }
    return esm;
}


