#!/usr/bin/env node
const program = require('commander');       // the command-line interface
const sol     = require('./sol.run.js');    // the commands
const sh      = require('./sol.shell.js');  // the interactive interface
const batch   = require('../src/batch');    // the batch interface
/*
 *  This file is the command-line interface
*/
program
    .name('sol')
    .description('Command line and interactive shell tool for Solid')
    .version("0.1.0")
;  
program
    .command('shell')
    .alias('sh')
    .description('run as an interactive shell')
    .action( () => {
        sol("login").then(()=>{sh()},err=>console.log(err));
    });
program
    .command('read <URL>')
    .alias('r')
    .description('read a remote file')
    .action( (URL) => {
        sol("login").then( ()=> { 
            sol("read",[URL]).then(()=>{
            },err=>console.log(err));
        },err=>console.log(err));
    });
program
    .command('readFolder <URL>')
    .alias('rf')
    .description("list a remote folder's contents")
    .action( (URL) => {
        sol("login").then( ()=> { 
            sol("read",["folder",URL]).then(()=>{
            },err=>console.log(err));
        },err=>console.log(err));
    });
program
    .command('createFolder <URL...>')
    .alias('cf')
    .description('create one or more remote folders')
    .action( URL => {
        sol("login").then( ()=> { 
            sol("createFolder",[URL]).then(()=>{
            },err=>console.log(err));
        },err=>console.log(err));
    });
program
    .command('delete <URL...>')
    .alias('rm')
    .description('delete remote file(s_ or empty folder(s)')
    .action( URL => {
        sol("login").then( ()=> { 
            sol("delete",[URL]).then(()=>{
            },err=>console.log(err));
        },err=>console.log(err));
    });
program
    .command('upload <target> <files...>')
    .alias("up")
    .description('upload file(s) to a Solid server')
    .action( (target,files) => {
        sol("login").then( ()=>{ 
            sol("upload",[target,files]).then( ()=>{
            },err=>console.log(err));
        },err=>console.log(err));
     },err=>console.log(err));
program
    .command('download <target> <URL>')
    .alias("dn")
    .description('download a remote file')
    .action( (target,URL) => {
        sol("login").then( ()=>{ 
            sol("download",[target,URL]).then( ()=>{
            },err=>console.log(err));
        },err=>console.log(err));
    });
program
    .command('copy <oldURL> <newURL>')
    .alias('cp')
    .description('copy a remote file to a remote location')
    .action( (oldURL,newURL) => {
        sol("login").then( ()=> { 
            sol("copy",[oldURL,newURL]).then(()=>{
            },err=>console.log(err));
        },err=>console.log(err));
    });
program
    .command('copyFolder <oldURL> <newURL>')
    .alias('cpf')
    .description('deep copy a remote folder to a remote loc.')
    .action( (oldURL,newURL) => {
        sol("login").then( ()=> { 
            sol("copyFolder",[oldURL,newURL]).then(()=>{
            },err=>console.log(err));
        },err=>console.log(err));
    });
/* TBD
program
    .command('batch <scriptFile>')
    .description('batch run commands in a script file')
    .action( (scriptFile) => {
        sol("login").then(()=>{
            sol("batch",[scriptFile]).then(()=>{
            },err=>console.log(err) )
        },err=>console.log(err) )
    },err=>console.log(err))
*/
if(process.argv.length<3){
    process.argv.push("-h");
}
program.parse(process.argv);


